---
apiVersion: v1
kind: Service
metadata:
  name: "file-server-service"
spec:
  type: ClusterIP
  selector:
    app: file-server-label
  ports:
    - name: proxied
      port: 80
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-server-label
  template:
    metadata:
      labels:
        app: file-server-label  
    spec:
      containers:
        - name: file-server-container
          image: {{ .Values.image.registry }}/{{ .Values.image.name }}
          ports:
            - containerPort: 8080
              name: http
          resources:
            limits:
              cpu: 50m
              memory: 128Mi
