apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-label
  template:
    metadata:
      labels:
        app: blog-label  
    spec:
      containers:
        - name: blog-container
          image: {{ .Values.blog.image.registry }}/{{ .Values.blog.image.name }}
          ports:
            - containerPort: 8080
              name: http
