apiVersion: v1
kind: Service
metadata:
  name: tunnel-metrics
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/part-of: tunnel
spec:
  type: ClusterIP
  selector:
    app: cloudflared
  ports:
    - name: proxied
      port: 80
      targetPort: metrics