apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tunnel
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: tunnel
  namespaceSelector:
    any: true
  endpoints:
    - port: metrics