apiVersion: apps/v1
kind: Deployment
metadata:
  name: files
spec:
  replicas: 1
  selector:
    matchLabels:
      app: files-label
  template:
    metadata:
      labels:
        app: files-label  
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
        - name: files-container
          image: {{ .Values.files.image.registry }}/{{ .Values.files.image.name }}
          ports:
            - containerPort: 8080
              name: http
          resources:
            limits:
              cpu: 50m
              memory: 128Mi
          volumeMounts:
            - mountPath: "/files/mnt"
              name: task-pv-storage